spring:
  application:
    name: userService
  profiles:
    active: dev
  config:
    import: configserver:http://master:1234@localhost:9000
  devtools:
    restart:
      enabled: true
      additional-exclude: static
    livereload:
      enabled: true